### ISSUE TITLE
Rapier?

### ISSUE THREAD

**Issue by fanjules** [cx20/webgl-physics-examples#111]
It would be great if you included Rapier.js physics engine, to spread the word about this great library.

I've found it to be the best of the three.js physics engines - fast and easy to use, feels a lot like when I would work with PhysX.

**Comment by cx20** [comment]
Thank you for telling me that. I would love to find the time to try it.

**Comment by cx20** [comment]
Below is a link for future reference.

three.js + Rapier sample
https://threejs.org/examples/?q=rapi#physics_rapier_instancing

Babylon.js + Rapier sample
https://forum.babylonjs.com/t/the-debug-rendering-for-the-rapier3d-compat-physics-engine-and-babylon-js/42283

**Comment by cx20** [comment]
https://github.com/cx20/webgl-physics-examples/pull/144
https://github.com/cx20/webgl-physics-examples/pull/145
