### ISSUE TITLE
Textures are not displayed after changing the Hilo3d library from 1.13.18 to 1.15.1

### ISSUE THREAD

**Issue by cx20** [cx20/webgl-physics-examples#24]
I tried changing the Hilo3d library from `1.13.18` to `1.15.1`.
However, the texture is no longer displayed.

https://cx20.github.io/webgl-physics-examples/examples/hilo3d/oimo/minimum/
![image](https://user-images.githubusercontent.com/1833979/86472690-89931900-bd7a-11ea-9654-026aa41880b0.png)

no error is displayed on the console.

@06wj Do you have any advice?

**Comment by 06wj** [comment]
Sorry, the old version will be displayed as `unlit material` by default when there is no light. The new version must be added with light or set material.lightType to reduce misleading.

You can solve according to the following two solutions:

```stage.addChild(new Hilo3d.AmbientLight());```
or
```
material: new Hilo3d.BasicMaterial({
    lightType: 'NONE',
    diffuse:new Hilo3d.LazyTexture({
        src:'../../../../assets/textures/frog.jpg'
    })
})```

**Comment by cx20** [comment]
@06wj Thanks for your advice it is now displayed.

[latest sample result:](https://rawcdn.githack.com/cx20/webgl-physics-examples/74815979130f2a476e220dab65b0138293020e24/examples/hilo3d/oimo/minimum/index.html)

![image](https://user-images.githubusercontent.com/1833979/86503945-13c89500-bdee-11ea-8384-b015e827d684.png)

https://github.com/cx20/webgl-physics-examples/pull/25
