### ISSUE TITLE
use newer active cannon-es fork 

### ISSUE THREAD

**Issue by arpu** [cx20/webgl-physics-examples#28]
i think it would be nice to use 

https://github.com/react-spring/cannon-es

**Comment by cx20** [comment]
I'm sorry, I'm late to notice your report.
I would like to work on it.

**Comment by cx20** [comment]
I have added cannon-es samples to the list

https://github.com/cx20/webgl-physics-examples#minimum-examples
![image](https://user-images.githubusercontent.com/1833979/120045127-3557ee00-c04a-11eb-8e75-030f3708178e.png)
